"""
Leagues router — /leagues/*

Endpoints:
  POST  /leagues                                          Create a new league
  POST  /leagues/join/{invite_code}                       Submit a join request via invite link
  GET   /leagues/{league_id}                              Get league details (members only)
  GET   /leagues/{league_id}/members                      List approved members
  PATCH /leagues/{league_id}/members/{user_id}/role       Change a member's role (manager only)
  DELETE /leagues/{league_id}/members/{user_id}           Remove a member (manager only)
  GET   /leagues/{league_id}/requests                     List pending join requests (manager only)
  POST  /leagues/{league_id}/requests/{user_id}/approve   Approve a join request (manager only)
  DELETE /leagues/{league_id}/requests/{user_id}          Deny/delete a join request (manager only)
  GET   /leagues/{league_id}/tournaments                  List league's selected tournaments
  PUT   /leagues/{league_id}/tournaments                  Replace league's tournament schedule (manager only)
"""

import datetime
import uuid

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session, joinedload

from app.database import get_db
from app.dependencies import get_current_user, get_league_or_404, require_league_manager, require_league_member
from app.models import (
    League,
    LeagueMember,
    LeagueMemberRole,
    LeagueMemberStatus,
    LeagueTournament,
    Season,
    Tournament,
    User,
)
from app.schemas.league import LeagueCreate, LeagueMemberOut, LeagueOut, LeagueUpdate, LeagueJoinPreview, LeagueRequestOut, RoleUpdate
from app.schemas.tournament import LeagueTournamentOut, TournamentOut

router = APIRouter(prefix="/leagues", tags=["leagues"])

# ---------------------------------------------------------------------------
# League creation
# ---------------------------------------------------------------------------


@router.post("", response_model=LeagueOut, status_code=201)
def create_league(
    body: LeagueCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Create a new league. The creator is automatically made an approved admin.
    An active season for the current calendar year is created. All leagues are
    private by default — joining requires an invite link and manager approval.
    """
    league = League(
        name=body.name,
        description=body.description,
        no_pick_penalty=body.no_pick_penalty,
        created_by=current_user.id,
        # is_public defaults to False; invite_code auto-generated by model default
    )
    db.add(league)
    db.flush()  # Get the league ID before adding related objects.

    # Auto-add creator as an approved league manager — no approval step needed for the founder.
    membership = LeagueMember(
        league_id=league.id,
        user_id=current_user.id,
        role=LeagueMemberRole.MANAGER.value,
        status=LeagueMemberStatus.APPROVED.value,
    )
    db.add(membership)

    # Create the initial season for the current year.
    season = Season(league_id=league.id, year=datetime.date.today().year, is_active=True)
    db.add(season)

    db.commit()
    db.refresh(league)
    return league


# ---------------------------------------------------------------------------
# Invite-code join
# ---------------------------------------------------------------------------


@router.get("/join/{invite_code}", response_model=LeagueJoinPreview)
def preview_join(
    invite_code: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Preview a league before submitting a join request.

    Returns the league name, description, member count, and the current user's
    relationship to it (None = no request, "pending" = waiting, "approved" = member).
    Does not create or modify any records.
    """
    league = db.query(League).filter_by(invite_code=invite_code).first()
    if not league:
        raise HTTPException(status_code=404, detail="Invalid invite link — league not found")

    member_count = db.query(LeagueMember).filter_by(
        league_id=league.id, status=LeagueMemberStatus.APPROVED.value
    ).count()

    existing = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=current_user.id
    ).first()

    return LeagueJoinPreview(
        league_id=league.id,
        name=league.name,
        description=league.description,
        member_count=member_count,
        user_status=existing.status if existing else None,
    )


@router.get("/my-requests", response_model=list[LeagueRequestOut])
def my_join_requests(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return the current user's pending join requests across all leagues."""
    rows = (
        db.query(LeagueMember, League)
        .join(League, LeagueMember.league_id == League.id)
        .filter(
            LeagueMember.user_id == current_user.id,
            LeagueMember.status == LeagueMemberStatus.PENDING.value,
        )
        .all()
    )
    return [
        LeagueRequestOut(
            league_id=league.id,
            league_name=league.name,
            league_description=league.description,
            requested_at=member.joined_at,
        )
        for member, league in rows
    ]


@router.post("/join/{invite_code}", response_model=LeagueMemberOut, status_code=201)
def request_to_join(
    invite_code: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Submit a join request using a league's invite code.

    Private leagues (default): creates a "pending" membership. A league manager must
    approve before the user has access to the league.

    Public leagues (future): auto-approves and returns an "approved" membership.

    The invite code is shared by league managers; it is the only way to request
    membership. Admins can find their invite link in the Admin panel.
    """
    league = db.query(League).filter_by(invite_code=invite_code).first()
    if not league:
        raise HTTPException(status_code=404, detail="Invalid invite link — league not found")

    existing = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=current_user.id
    ).first()
    if existing:
        if existing.status == LeagueMemberStatus.APPROVED.value:
            raise HTTPException(status_code=409, detail="You are already a member of this league")
        raise HTTPException(status_code=409, detail="You already have a pending join request for this league")

    # Public leagues skip the approval step.
    initial_status = (
        LeagueMemberStatus.APPROVED.value
        if league.is_public
        else LeagueMemberStatus.PENDING.value
    )

    membership = LeagueMember(
        league_id=league.id,
        user_id=current_user.id,
        role=LeagueMemberRole.MEMBER.value,
        status=initial_status,
    )
    db.add(membership)
    db.commit()
    db.refresh(membership)
    membership.user = current_user
    return membership


# ---------------------------------------------------------------------------
# League detail & membership management
# ---------------------------------------------------------------------------


@router.get("/{league_id}", response_model=LeagueOut)
def get_league(
    league_and_member: tuple[League, LeagueMember] = Depends(require_league_member),
):
    """Return league details including invite_code. Requires approved membership."""
    league, _ = league_and_member
    return league


@router.patch("/{league_id}", response_model=LeagueOut)
def update_league(
    body: LeagueUpdate,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Update league name, description, or no_pick_penalty. Requires league manager."""
    league, _ = league_and_manager
    if body.name is not None:
        league.name = body.name
    if body.description is not None:
        league.description = body.description
    if body.no_pick_penalty is not None:
        league.no_pick_penalty = body.no_pick_penalty
    db.commit()
    db.refresh(league)
    return league


@router.get("/{league_id}/members", response_model=list[LeagueMemberOut])
def list_members(
    league_and_member: tuple[League, LeagueMember] = Depends(require_league_member),
    db: Session = Depends(get_db),
):
    """List approved members of a league. Requires membership."""
    league, _ = league_and_member
    return (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, status=LeagueMemberStatus.APPROVED.value)
        .options(joinedload(LeagueMember.user))
        .all()
    )


@router.patch("/{league_id}/members/{user_id}/role", response_model=LeagueMemberOut)
def update_member_role(
    user_id: uuid.UUID,
    body: RoleUpdate,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Change an approved member's role. Requires league manager."""
    league, _ = league_and_manager

    if body.role not in (LeagueMemberRole.MANAGER.value, LeagueMemberRole.MEMBER.value):
        raise HTTPException(status_code=400, detail="Role must be 'manager' or 'member'")

    membership = (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, user_id=user_id, status=LeagueMemberStatus.APPROVED.value)
        .options(joinedload(LeagueMember.user))
        .first()
    )
    if not membership:
        raise HTTPException(status_code=404, detail="Member not found")

    membership.role = body.role
    db.commit()
    db.refresh(membership)
    return membership


@router.delete("/{league_id}/members/{user_id}", status_code=204)
def remove_member(
    user_id: uuid.UUID,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Remove an approved member from a league. Requires league manager."""
    league, manager_membership = league_and_manager

    if user_id == manager_membership.user_id:
        raise HTTPException(status_code=400, detail="You cannot remove yourself from the league")

    membership = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=user_id, status=LeagueMemberStatus.APPROVED.value
    ).first()
    if not membership:
        raise HTTPException(status_code=404, detail="Member not found")

    db.delete(membership)
    db.commit()


# ---------------------------------------------------------------------------
# Join request management (manager only)
# ---------------------------------------------------------------------------


@router.get("/{league_id}/requests", response_model=list[LeagueMemberOut])
def list_join_requests(
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """List pending join requests. Requires league manager."""
    league, _ = league_and_manager
    return (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, status=LeagueMemberStatus.PENDING.value)
        .options(joinedload(LeagueMember.user))
        .all()
    )


@router.post("/{league_id}/requests/{user_id}/approve", response_model=LeagueMemberOut)
def approve_join_request(
    user_id: uuid.UUID,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Approve a pending join request. Requires league manager."""
    league, _ = league_and_manager

    membership = (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, user_id=user_id, status=LeagueMemberStatus.PENDING.value)
        .options(joinedload(LeagueMember.user))
        .first()
    )
    if not membership:
        raise HTTPException(status_code=404, detail="Pending request not found")

    membership.status = LeagueMemberStatus.APPROVED.value
    db.commit()
    db.refresh(membership)
    return membership


@router.delete("/{league_id}/requests/me", status_code=204)
def cancel_my_join_request(
    league: League = Depends(get_league_or_404),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Cancel the current user's own pending join request."""
    membership = db.query(LeagueMember).filter_by(
        league_id=league.id,
        user_id=current_user.id,
        status=LeagueMemberStatus.PENDING.value,
    ).first()
    if not membership:
        raise HTTPException(status_code=404, detail="No pending request found")

    db.delete(membership)
    db.commit()


@router.delete("/{league_id}/requests/{user_id}", status_code=204)
def deny_join_request(
    user_id: uuid.UUID,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """
    Deny and delete a pending join request. Requires league manager.
    Denied requests are deleted rather than stored to keep the table clean
    and allow the user to request again later if needed.
    """
    league, _ = league_and_manager

    membership = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=user_id, status=LeagueMemberStatus.PENDING.value
    ).first()
    if not membership:
        raise HTTPException(status_code=404, detail="Pending request not found")

    db.delete(membership)
    db.commit()


# ---------------------------------------------------------------------------
# Tournament schedule
# ---------------------------------------------------------------------------


def _build_league_tournament_out(row: LeagueTournament) -> LeagueTournamentOut:
    """Build a LeagueTournamentOut from a LeagueTournament row, resolving effective_multiplier."""
    t = row.tournament
    effective = row.multiplier if row.multiplier is not None else t.multiplier
    return LeagueTournamentOut(
        id=t.id,
        pga_tour_id=t.pga_tour_id,
        name=t.name,
        start_date=t.start_date,
        end_date=t.end_date,
        multiplier=t.multiplier,
        purse_usd=t.purse_usd,
        status=t.status,
        is_team_event=t.is_team_event,
        effective_multiplier=effective,
    )


@router.get("/{league_id}/tournaments", response_model=list[LeagueTournamentOut])
def get_league_tournaments(
    league_and_member: tuple[League, LeagueMember] = Depends(require_league_member),
    db: Session = Depends(get_db),
):
    """
    Return the tournaments selected for this league's schedule, sorted by
    start_date ascending. Each tournament includes effective_multiplier, which
    resolves to the league's per-tournament override or the global default.
    Returns [] if the admin hasn't configured the schedule yet.
    """
    league, _ = league_and_member
    rows = (
        db.query(LeagueTournament)
        .filter_by(league_id=league.id)
        .join(LeagueTournament.tournament)
        .order_by(Tournament.start_date.asc())
        .all()
    )
    return [_build_league_tournament_out(row) for row in rows]


class TournamentScheduleItem(BaseModel):
    tournament_id: uuid.UUID
    multiplier: float | None = None  # None = inherit from tournament.multiplier


class TournamentScheduleUpdate(BaseModel):
    tournaments: list[TournamentScheduleItem]


@router.put("/{league_id}/tournaments", response_model=list[LeagueTournamentOut])
def update_league_tournaments(
    body: TournamentScheduleUpdate,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """
    Atomically replace the league's tournament schedule.

    Accepts a full list of {tournament_id, multiplier} objects. Multiplier
    may be null to inherit the tournament's global default. Existing rows not
    in the new list are deleted; new rows are inserted. Returns the updated
    sorted schedule.
    Requires league manager.
    """
    league, _ = league_and_manager

    tournament_ids = [item.tournament_id for item in body.tournaments]

    # Verify all requested tournament IDs actually exist.
    if tournament_ids:
        found = db.query(Tournament).filter(Tournament.id.in_(tournament_ids)).count()
        if found != len(tournament_ids):
            raise HTTPException(status_code=422, detail="One or more tournament IDs not found")

    # Atomic replace: delete all existing selections, insert new ones.
    db.query(LeagueTournament).filter_by(league_id=league.id).delete()
    for item in body.tournaments:
        db.add(LeagueTournament(
            league_id=league.id,
            tournament_id=item.tournament_id,
            multiplier=item.multiplier,
        ))
    db.commit()

    rows = (
        db.query(LeagueTournament)
        .filter_by(league_id=league.id)
        .join(LeagueTournament.tournament)
        .order_by(Tournament.start_date.asc())
        .all()
    )
    return [_build_league_tournament_out(row) for row in rows]
